"use client";

import React from 'react';
import { Sparkles } from 'lucide-react';

export default function PortfolioBuilderBadge() {
  const handleClick = () => {
    // Get the base URL (current origin) and navigate to home
    const baseUrl = window.location.origin;
    window.open(baseUrl, '_blank', 'noopener,noreferrer');
  };

  return (
    <button
      onClick={handleClick}
      className="fixed bottom-6 right-6 z-50 flex items-center gap-2 px-4 py-2.5 bg-gradient-to-r from-purple-600 to-pink-600 hover:from-purple-700 hover:to-pink-700 text-white text-sm font-medium rounded-full shadow-lg shadow-purple-500/50 hover:shadow-purple-500/70 transition-all duration-300 hover:scale-105 active:scale-95 group"
      aria-label="Generated by Portfolio Builder - Visit Portfolio Builder"
      title="Generated by Portfolio Builder"
    >
      <Sparkles className="w-4 h-4 group-hover:rotate-12 transition-transform duration-300" />
      <span className="hidden sm:inline">Generated by Portfolio Builder</span>
      <span className="sm:hidden">Portfolio Builder</span>
    </button>
  );
}



